### PR TITLE
translate section names and descriptions

### PR DESCRIPTION
**Pull request by KaitCrawford**

### CODE REVIEW

**Comment by KaitCrawford** [comment]
@miltontony ready for review

**Comment by miltontony** [comment]
@KaitCrawford :cake: :cake: :fireworks: :star: :star2: 
just needs a test though.. :wink:

**Comment by KaitCrawford** [comment]
@miltontony now with added testing goodness!! :smile:

**Comment by miltontony** [comment]
:+1: 
wonderful!!! :cake: :star2:

**Pull request merged**
