### PR TITLE
Terms page

### PR DESCRIPTION
**Pull request by Rizziepit**

### CODE REVIEW

**Comment by Rizziepit** [comment]
This implements the "about" / "terms" page. Not done yet - it's waiting for copy.

**Comment by miltontony** [comment]
Very hacky, but don't see a way around this at the moment since this app has no data store of it's own.

**Comment by miltontony** [comment]
Perhaps we should consider creating a repo for it and create a `unicore-cms-django` instance that will write the about/terms pages. Possibly extending it to have a model for the persona's in the next phase of dev? cc: @smn

**Comment by smn** [comment]
Why don't we add a flatpage thing to our content repos?

**Comment by Rizziepit** [comment]
We can. The simplest version is to simply search all repos for the given slug. But that means content editors will have to push IoGT-specific pages to repos where they don't belong.

**Comment by miltontony** [comment]
@smn sorry, a bit of background is probably needed. This iogt app isn't backed by a content repo. Since it's an aggregator, it doesn't have it's own content to pull terms from, hence my suggestion that maybe it needs one.

**Comment by smn** [comment]
ah got it, thanks @Miltontony.

On 24 June 2015 at 12:18, Milton Madanda notifications@github.com wrote:

> @smn https://github.com/smn sorry, a bit of background is probably
> needed. This iogt app isn't backed by a content repo. Since it's an
> aggregator, it doesn't have it's own content to pull terms from, hence my
> suggestion that maybe it needs one.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/universalcore/springboard-iogt/pull/9#issuecomment-114815702
> .

## 

Simon de Haan | Chief Engineer Praekelt Foundation

praekeltfoundation.org | praekelt.com
M: +27 (0) 76 449 3806  |  http://twitter.com/smn

**Comment by Rizziepit** [comment]
@miltontony can I merge this for the time being? Once UCD and latest mission control are in production, we will get the "master" repo for free. I suggest we update IoGT's logic at that point.

**Comment by miltontony** [comment]
:+1:

**Pull request merged**
