### PR TITLE
set persona value on GA

### PR DESCRIPTION
**Pull request by Rizziepit**

### CODE REVIEW

**Comment by Rizziepit** [comment]
@miltontony @smn ready for review.

I couldn't make up my mind about the GA implementation. So I added support for a custom dimension while putting the persona value in the GA path query string. Happy to change this.

**Comment by miltontony** [comment]
:+1: 
I think having both is fine

**Comment by smn** [comment]
We control our GA domains so we should be able to set the custom dimensions / tags via the API.
That's a lot more work though and will probably involve unicore-mc, happy to leave that for later?

**Comment by Rizziepit** [comment]
I'm going to leave that for later. Until then, the query string hack should be good enough.

**Pull request merged**
