### PR TITLE
update translations again

### PR DESCRIPTION
**Pull request by g1039**
Please review

### CODE REVIEW

**Comment by hodgestar** [comment]
@TrevorOctober Do you have an example of a string that we suspect wasn't translated before and is translated now? I'm not seeing any updates to actual messages, so I'm just wondering which messages we're expecting to be fixed.

**Comment by g1039** [comment]
@hodgestar The “know and use them” translations doesn't pull through in Pootle (please see http://00-iogt.apollo.unicore.io/)

**Comment by hodgestar** [comment]
@TrevorOctober If you look at the changes in this PR, you'll notice that they don't include any updates for the "know and use them" phrase. Any idea what happened?

**Comment by miltontony** [comment]
:+1:

**Pull request merged**
